import 'package:flutter/material.dart';
import 'core/theme/app_theme.dart';
import 'features/auth/auth_screens.dart';
import 'features/student/student_screens.dart';
import 'features/assessment/assessment_screens.dart';
import 'features/advisor/admin_screens.dart';
import 'models/app_models.dart';

void main()=>runApp(const SmartEducationalApp());
class SmartEducationalApp extends StatelessWidget { const SmartEducationalApp({super.key}); @override Widget build(BuildContext context)=>MaterialApp(title:'المستشار التعليمي الذكي',debugShowCheckedModeBanner:false,theme:AppTheme.light(),darkTheme:AppTheme.dark(),themeMode:ThemeMode.system,locale:const Locale('ar'),builder:(context,child)=>Directionality(textDirection:TextDirection.rtl,child:child!),initialRoute:'/splash',onGenerateRoute:_routes); }
Route<dynamic> _route(Widget page)=>PageRouteBuilder(pageBuilder:(_,__,___)=>page,transitionsBuilder:(_,animation,__,child)=>FadeTransition(opacity:animation,child:child));
Route<dynamic> _routes(RouteSettings settings){switch(settings.name){case '/splash':return _route(const SplashScreen());case '/onboarding':return _route(const OnboardingScreen());case '/login':return _route(const LoginScreen());case '/register':return _route(const RegisterScreen());case '/forgot-password':return _route(const ForgotPasswordScreen());case '/reset-password':return _route(const ResetPasswordScreen());case '/student/home':return _route(const StudentShell());case '/student/majors':return _route(const MajorsScreen());case '/student/consultations':return _route(const ConsultationsScreen());case '/student/appointments':return _route(const AppointmentsScreen());case '/student/notifications':return _route(const NotificationsScreen());case '/student/profile':return _route(const ProfileScreen());case '/student/settings':return _route(const SettingsScreen());case '/student/test':return _route(const AssessmentIntroScreen());case '/student/test/quiz':return _route(const QuizScreen());case '/student/test-result':return _route(ResultsScreen(results:settings.arguments! as List<RecommendationModel>));case '/student/major-details':return _route(MajorDetailsScreen(major:settings.arguments! as MajorModel));case '/student/chat':return _route(ChatScreen(consultation:settings.arguments! as ConsultationModel));case '/advisor/dashboard':return _route(const AdvisorDashboard());case '/admin/dashboard':return _route(const AdminDashboard());case '/admin/management':return _route(ManagementScreen(title:settings.arguments! as String));default:return _route(const LoginScreen());}}
class SplashScreen extends StatefulWidget { const SplashScreen({super.key});@override State<SplashScreen> createState()=>_SplashScreenState();}class _SplashScreenState extends State<SplashScreen> with SingleTickerProviderStateMixin{late final AnimationController controller;@override void initState(){super.initState();controller=AnimationController(vsync:this,duration:const Duration(milliseconds:900))..forward();Future.delayed(const Duration(seconds:2),(){if(mounted)Navigator.pushReplacementNamed(context,'/onboarding');});}@override void dispose(){controller.dispose();super.dispose();}@override Widget build(BuildContext context)=>Scaffold(body:Center(child:ScaleTransition(scale:CurvedAnimation(parent:controller,curve:Curves.easeOutBack),child:Column(mainAxisSize:MainAxisSize.min,children:[CircleAvatar(radius:50,backgroundColor:Theme.of(context).colorScheme.primary,child:const Icon(Icons.school_rounded,size:52,color:Colors.white)),const SizedBox(height:18),Text('المستشار التعليمي الذكي',style:Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.bold)),const SizedBox(height:6),const Text('Smart Educational Advisory')]))));}
class OnboardingScreen extends StatefulWidget { const OnboardingScreen({super.key});@override State<OnboardingScreen> createState()=>_OnboardingScreenState();}class _OnboardingScreenState extends State<OnboardingScreen>{final page=PageController();int index=0;final items=const [(Icons.explore_rounded,'اكتشف تخصصك المناسب','ساعد نفسك في اكتشاف التخصص الذي يتناسب مع اهتماماتك وقدراتك.'),(Icons.quiz_rounded,'اختبر ميولك ومهاراتك','أجب عن مجموعة من الأسئلة واحصل على تحليل ذكي.'),(Icons.auto_awesome_rounded,'احصل على توصيات مخصصة','شاهد التخصصات المناسبة لك ونسبة التوافق لكل تخصص.'),(Icons.forum_rounded,'تواصل مع مستشار أكاديمي','اطلب الاستشارة واحجز موعداً مع المستشار.')];@override void dispose(){page.dispose();super.dispose();}@override Widget build(BuildContext context)=>Scaffold(body:SafeArea(child:Column(children:[Align(alignment:Alignment.centerLeft,child:TextButton(onPressed:()=>Navigator.pushReplacementNamed(context,'/login'),child:const Text('تخطي'))),Expanded(child:PageView.builder(controller:page,itemCount:items.length,onPageChanged:(v)=>setState(()=>index=v),itemBuilder:(_,i){final x=items[i];return Padding(padding:const EdgeInsets.all(32),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[CircleAvatar(radius:70,backgroundColor:Theme.of(context).colorScheme.primaryContainer,child:Icon(x.$1,size:70,color:Theme.of(context).colorScheme.primary)),const SizedBox(height:36),Text(x.$2,textAlign:TextAlign.center,style:Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.bold)),const SizedBox(height:16),Text(x.$3,textAlign:TextAlign.center,style:Theme.of(context).textTheme.bodyLarge)])})),Row(mainAxisAlignment:MainAxisAlignment.center,children:List.generate(items.length,(i)=>AnimatedContainer(duration:const Duration(milliseconds:250),margin:const EdgeInsets.all(4),width:i==index?24:8,height:8,decoration:BoxDecoration(color:i==index?Theme.of(context).colorScheme.primary:Colors.grey.shade400,borderRadius:BorderRadius.circular(9))))),Padding(padding:const EdgeInsets.all(24),child:FilledButton(onPressed:(){if(index==items.length-1){Navigator.pushReplacementNamed(context,'/login');}else{page.nextPage(duration:const Duration(milliseconds:300),curve:Curves.easeOut);}},style:FilledButton.styleFrom(minimumSize:const Size.fromHeight(52)),child:Text(index==items.length-1?'ابدأ الآن':'التالي')))])));}
