import 'package:flutter/material.dart';
import '../models/app_models.dart';
class AppButton extends StatelessWidget { const AppButton({super.key,required this.label,required this.onPressed, this.icon}); final String label; final VoidCallback? onPressed; final IconData? icon; @override Widget build(BuildContext context)=>FilledButton.icon(onPressed:onPressed,icon:icon==null?const SizedBox.shrink():Icon(icon),label:Text(label),style:FilledButton.styleFrom(minimumSize:const Size.fromHeight(52),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(16)))); }
class AppTextField extends StatelessWidget { const AppTextField({super.key,required this.label, this.controller,this.validator,this.obscureText=false,this.keyboardType}); final String label; final TextEditingController? controller; final String? Function(String?)? validator; final bool obscureText; final TextInputType? keyboardType; @override Widget build(BuildContext context)=>TextFormField(controller:controller,validator:validator,obscureText:obscureText,keyboardType:keyboardType,decoration:InputDecoration(labelText:label)); }
class SectionTitle extends StatelessWidget { const SectionTitle(this.title,{super.key,this.action}); final String title; final Widget? action; @override Widget build(BuildContext context)=>Padding(padding:const EdgeInsets.only(top:24,bottom:12),child:Row(children:[Text(title,style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.bold)),const Spacer(),if(action!=null) action!])); }
class StatCard extends StatelessWidget { const StatCard({super.key,required this.label,required this.value,required this.icon, this.color}); final String label,value; final IconData icon; final Color? color; @override Widget build(BuildContext context)=>Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[CircleAvatar(backgroundColor:(color??Theme.of(context).colorScheme.primary).withOpacity(.12),foregroundColor:color??Theme.of(context).colorScheme.primary,child:Icon(icon)),const SizedBox(height:14),Text(value,style:Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.bold)),Text(label,style:Theme.of(context).textTheme.bodySmall)]))); }
class MajorCard extends StatelessWidget { const MajorCard({super.key,required this.major,this.score,this.onTap}); final MajorModel major; final double? score; final VoidCallback? onTap; @override Widget build(BuildContext context)=>Card(child:InkWell(onTap:onTap,borderRadius:BorderRadius.circular(22),child:Padding(padding:const EdgeInsets.all(16),child:Row(children:[CircleAvatar(radius:25,child:Icon(major.category=='التقنية'?Icons.memory_rounded:Icons.business_center_rounded)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(major.name,style:const TextStyle(fontWeight:FontWeight.bold,fontSize:16)),const SizedBox(height:4),Text(major.description,maxLines:2,overflow:TextOverflow.ellipsis),if(score!=null)...[const SizedBox(height:10),LinearProgressIndicator(value:score!/100,borderRadius:BorderRadius.circular(8)),Text('${score!.round()}% توافق',style:TextStyle(color:Theme.of(context).colorScheme.primary,fontWeight:FontWeight.bold))]]),const Icon(Icons.chevron_left)])))); }
class EmptyState extends StatelessWidget { const EmptyState({super.key,required this.title,required this.description,this.action}); final String title,description; final Widget? action; @override Widget build(BuildContext context)=>Center(child:Padding(padding:const EdgeInsets.all(32),child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(Icons.auto_awesome_outlined,size:64,color:Theme.of(context).colorScheme.primary),const SizedBox(height:16),Text(title,style:Theme.of(context).textTheme.titleLarge),const SizedBox(height:8),Text(description,textAlign:TextAlign.center),if(action!=null)...[const SizedBox(height:16),action!]]))); }
class ConfirmDialog { static Future<bool> show(BuildContext context,{required String title,required String content}) async => await showDialog<bool>(context:context,builder:(context)=>AlertDialog(title:Text(title),content:Text(content),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('إلغاء')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('تأكيد'))]))??false; }
