import 'package:flutter/material.dart';
import '../../../../data/mock/mock_data.dart';
import '../../data/repositories/mock_chat_repositories.dart';
import '../controllers/chat_controller.dart';
import '../widgets/chat_input.dart';
import '../widgets/date_separator.dart';
import '../widgets/message_bubble.dart';
import '../widgets/typing_indicator.dart';
class ChatScreen extends StatefulWidget { const ChatScreen({super.key, required this.consultationId}); final String consultationId; @override State<ChatScreen> createState() => _ChatScreenState(); }
class _ChatScreenState extends State<ChatScreen> { late final ChatController controller; @override void initState() { super.initState(); controller = ChatController(conversationId: widget.consultationId, currentUserId: 'student-1', messages: MockMessageRepository(MockData.messages), reactions: MockReactionRepository())..load(); controller.addListener(_refresh); } void _refresh() => mounted ? setState(() {}) : null; @override void dispose() { controller.removeListener(_refresh); controller.dispose(); super.dispose(); } @override Widget build(BuildContext context) { final state = controller.state; return Scaffold(appBar: AppBar(title: Column(crossAxisAlignment: CrossAxisAlignment.start, children: <Widget>[Text(MockData.advisor.name), Text(state.isTyping ? 'يكتب الآن...' : MockData.advisor.lastSeen, style: Theme.of(context).textTheme.bodySmall)]), actions: <Widget>[IconButton(onPressed: () => Navigator.pushNamed(context, '/consultations/call'), icon: const Icon(Icons.call_outlined))]), body: state.isLoading ? const Center(child: CircularProgressIndicator()) : Column(children: <Widget>[Expanded(child: ListView(padding: const EdgeInsets.all(16), children: <Widget>[const DateSeparator(label: 'اليوم'), ...state.messages.map((message) => MessageBubble(message: message, isMine: message.senderId == 'student-1', onReply: controller.reply, onReact: controller.react, onDelete: controller.delete)), if (state.isTyping) TypingIndicator(name: MockData.advisor.name)])), ChatInput(replyText: state.replyTo?.text, onCancelReply: controller.clearReply, onSend: controller.sendText, onAttachment: controller.sendAttachment)])); } }
